project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
languages_mapping: &languages_mapping
  two_letters_code:
    'pt-BR': 'pt-BR'
files: [
    # JSON translation files
    {
      source: '/i18n/en/**/*',
      translation: '/i18n/%two_letters_code%/**/%original_file_name%',
      languages_mapping: *languages_mapping,
    },
    # Docs Markdown files
    {
      source: '/docs/**/*',
      translation: '/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%',
      ignore: [
        '/docs/components/**/*',
        '/docs/**/*.yml',
      ],
      languages_mapping: *languages_mapping,
    },
    # Docs Old versions
    {
      source: '/versioned_docs/**/*',
      translation: '/i18n/%two_letters_code%/docusaurus-plugin-content-docs/**/%original_file_name%',
      ignore: [
        '/versioned_docs/components/**/*',
        '/versioned_docs/**/*.yml',
      ],
      languages_mapping: *languages_mapping,
    },
    # Blog Markdown files
    {
      source: '/blog/**/*',
      translation: '/i18n/%two_letters_code%/docusaurus-plugin-content-blog/**/%original_file_name%',
      ignore: [
        '/**/*.yml',
      ],
      languages_mapping: *languages_mapping,
    },
  ]