/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    // 'welcome',
    // 'contributing-to-the-docs',
    // {
    //   type: 'category',
    //   label: '📌 Getting Started',
    //   collapsible: false,
    //   items: [
    //     {
    //       type: 'category',
    //       label: 'Tutorials & Examples',
    //       collapsed: false,
    //       items: [
    //         'getting-started/tutorials-and-examples/basic-hud-html',
    //       ]
    //     },
    //     'getting-started/game-modes-and-packages'
    //   ]
    // },
    // {
    //   type: 'category',
    //   label: '🎓 Core Concepts',
    //   collapsible: false,
    //   items: [
    //     {
    //       type: 'category',
    //       label: 'Tutorials & Examples',
    //       items: [
    //         'getting-started/tutorials-and-examples/basic-hud-html',
    //       ]
    //     },
    //     'getting-started/game-modes-and-packages'
    //   ]
    // },
    // {
    //   type: 'category',
    //   label: '👨‍💻 Scripting Reference',
    //   collapsible: false,
    //   items: [
    //     {
    //       type: 'category',
    //       label: 'Tutorials & Examples',
    //       items: [
    //         'getting-started/tutorials-and-examples/basic-hud-html',
    //       ]
    //     },
    //     'getting-started/game-modes-and-packages'
    //   ]
    // },
    // {
    //   type: 'category',
    //   label: '🎨 Assets & Modding',
    //   collapsible: false,
    //   items: [
    //     {
    //       type: 'category',
    //       label: 'Tutorials & Examples',
    //       items: [
    //         'getting-started/tutorials-and-examples/basic-hud-html',
    //       ]
    //     },
    //     'getting-started/game-modes-and-packages'
    //   ]
    // },
    // {
    //   type: 'category',
    //   label: '🛒 Vault & Marketplace',
    //   collapsible: false,
    //   items: [
    //     {
    //       type: 'category',
    //       label: 'Tutorials & Examples',
    //       items: [
    //         'getting-started/tutorials-and-examples/basic-hud-html',
    //       ]
    //     },
    //     'getting-started/game-modes-and-packages'
    //   ]
    // },
    {
      type: 'autogenerated',
      dirName: '.'
    }
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
