name: Test deployment

on:
  pull_request:
    branches:
      - master
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: nschloe/action-cached-lfs-checkout@v1
        with:
          fetch-depth: 0
          filter: blob:none
          submodules: true
          exclude: external/**

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Restore bundler cache
        uses: actions/cache@v4
        with:
          path: node_modules/.cache
          key: docusaurus-en-${{ runner.os }}-${{ hashFiles('yarn.lock', 'docusaurus.config.js') }}-${{ github.sha }}
          restore-keys: |
            docusaurus-en-${{ runner.os }}-${{ hashFiles('yarn.lock', 'docusaurus.config.js') }}-
            docusaurus-en-${{ runner.os }}-

      - name: Preprocess API
        run: yarn preprocess-api

      # - name: Download Crowdin
      #   env:
      #     CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
      #     CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
      #   run: yarn crowdin download

      - name: Test build website
        env:
          BUILD_EN_ONLY: true
        run: yarn build